### ISSUE TITLE
What about linux?

### ISSUE THREAD

**Issue by norkfy** [oaleynik/nwjs-autoupdater#5]
Hi, do you have any plans about linux support?

**Comment by tech4him1** [comment]
As far as I know, it should already work on linux.  You should just be able to follow all the steps in the [build instructions](https://github.com/oaleynik/nwjs-autoupdater/blob/master/README.md#build) except the ones for `rsrc` and the manifest, since you don't need a manifest except for Win32 applications.  I can't test it right now, but I would try this:
> 1) You need to have `golang` installed and properely configured ;)  
> 2) Install `glide` https://github.com/Masterminds/glide#install  
> 4) Clone this repo
> 7) Execute `glide install` to install dependencies  
> 8) Run `GOPATH=$(pwd) go build nwjs-autoupdater` to build for current platform.
If you are cross-compiling you should be able to use `GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o updater`.  Change the `GOARCH` to `386` if you are building for 32-bit linux.

**Comment by PoLaKoSz** [comment]
- Create `updater/updater_linux.go` with this content (maybe this can be optimized but i just wanted to make it work for now):
```go
package updater

import (
	"io/ioutil"
	"os"
	"path/filepath"
	"nwjs-autoupdater/unzip"
)

func Update(bundle, instDir, appName string) (error, string) {
	appExecName := appName
	appExec := filepath.Join(instDir, appExecName)
	appDir := appExec
	appBak := appExec + ".bak"

	tempDir, err := ioutil.TempDir("", appName)
	if err != nil {
		return err, appExec
	}
	defer os.RemoveAll(tempDir)

	err = unzip.Unzip(bundle, tempDir)
	if err != nil {
		return err, appExec
	}

	err = os.Rename(appDir, appBak)
	if err != nil {
		return err, appExec
	}

	updateFiles := filepath.Join(tempDir, appExecName)

	err = os.Rename(updateFiles, appExec)
	if err != nil {
		os.RemoveAll(appExec)
		os.Rename(appBak, appExec)

		return err, appExec
	}

	err = os.RemoveAll(appBak)
	if err != nil {
		return err, appExec
	}

	err = os.RemoveAll(bundle)
	if err != nil {
		return err, appExec
	}

	return nil, appExec
}

```

- Issue this command in the cloned root directory to create a temporary docker container to build the source code:
```sh
docker run --rm \
    --workdir /usr/local/go/src/nwjs-autoupdater \
    --volume "$PWD/src/nwjs-autoupdater:/usr/local/go/src/nwjs-autoupdater" \
    golang:1.12 \
    bash -c "go get github.com/Masterminds/glide && glide install && go build main.go"
```

Bumping Go version to 1.24 and using `go install github.com/Masterminds/glide@latest` produced an error for me so i went with an older Go version.
